### ISSUE TITLE
Infinite loop in the function "i2c_reset(i2c_t port)"

### ISSUE THREAD

**Issue by MalcolmReynlods** [electronicayciencia/wPi_soft_i2c#1]
Hi,
I am sorry if it's not the right way to bring up this issue. But I found no other option. I wanted to use multiple pins of RPi as SLC and SDA for many PCF8591 and I came across this code. I followed the instructions mentioned in the Readme. But still, it's not working properly. The problem I face is that the code goes into an infinite loop in the function 'i2c_reset(i2c_t port)' when it's calling the function 'digitalRead(port.sda)' which is always returning the value zero [line  88 in the file 'soft_i2c.c'].

**Comment by electronicayciencia** [comment]
Hi, thank you. 

You are right, loop in i2c_reset has no exit condition. I will change that part of code.

Anyways, I can think of two reasons that keep you reading 0 after a reset sequence:
 - Your i2c bus is not pulled-up, check your pull-up resistors.
 - There is another device that maintains the clock line down, it may be busy or defective.

Regards.

**Comment by MalcolmReynlods** [comment]
My circuit was a bit defective and now I have corrected it. Also, I tried pulling up the bus with different resistors, but I got a reading of '255' for all the cases throughout without any change. 

I only have a Raspberry Pi and a single PCF8591, so I guess no other device could interfere. 

Also, when I connect an oscilloscope to the SCL and SDA line, I did not see any signals.

**Comment by electronicayciencia** [comment]
Hello. I commited a fix to solve the infinite loop. Now it waits for some time for the bus to be released. After that time it returns and shows a warning message.

```
$ ./i2cli 25 24
I2C Command Line Interface
Warning: I2C Bus busy or defective.
...
i2cli> R
Warning: I2C Bus busy or defective.
i2cli>
```

Best regards.
